//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dimex002DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class imss_preautorizacion
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public Nullable<int> modified_by { get; set; }
        public string type { get; set; }
        public string txt1 { get; set; }
        public string txt2 { get; set; }
        public string txt3 { get; set; }
        public string txt4 { get; set; }
        public string txt5 { get; set; }
        public string txt6 { get; set; }
        public string txt7 { get; set; }
        public string txt8 { get; set; }
        public string txt9 { get; set; }
        public string txt10 { get; set; }
        public string txt11 { get; set; }
        public string txt12 { get; set; }
        public string txt13 { get; set; }
        public string txt14 { get; set; }
        public string txt15 { get; set; }
        public string txt16 { get; set; }
        public string txt17 { get; set; }
        public string txt18 { get; set; }
        public string txt19 { get; set; }
        public string txt20 { get; set; }
        public string txt21 { get; set; }
        public string txt22 { get; set; }
        public string txt23 { get; set; }
        public string txt24 { get; set; }
        public string txt25 { get; set; }
        public string txt26 { get; set; }
        public string txt27 { get; set; }
        public string txt28 { get; set; }
        public string txt29 { get; set; }
        public string txt30 { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<System.DateTime> date2 { get; set; }
        public Nullable<System.DateTime> date3 { get; set; }
        public Nullable<System.DateTime> date4 { get; set; }
        public Nullable<System.DateTime> date5 { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
    }
}
